version: "3.7"

services:
  postgresdb:
    image: postgres:11.1
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: gcr.io/sa-todo-list/todo-api:latest
    links:
      - postgresdb
    depends_on:
      - postgresdb
    ports:
      - 8080:8000
    restart: always
    environment:
      - DB_HOST=postgresdb
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL_MODE=disable
      - SERVER_PORT=8000
